import {
  LayoutDashboard,
  Users,
  GraduationCap,
  UserCheck,
  Heart,
  Shield,
  BookOpen,
  Layers,
  ClipboardList,
  FileText,
  Newspaper,
  HelpCircle,
  ScrollText,
  File,
  CreditCard,
  Receipt,
  RotateCcw,
  Tag,
  Headset,
  BarChart,
  FileBarChart,
  Activity,
  Settings,
  Cog,
  History,
  Video,
  CalendarCheck,
  FilePlus,
  FileUp,
  Clipboard,
  PenLine,
  MessageCircle,
  Megaphone,
  TrendingUp,
  User,
  Calendar,
  Star,
  Film,
  Clock,
  PenTool,
  Sigma,
  Award,
  MessagesSquare,
  Archive,
  Trophy,
  CalendarX,
  Mail,
  MessageSquare,
  Download,
  AlertCircle,
  AlertTriangle,
  FileCheck,
  Bell,
  LucideIcon,
} from "lucide-react";

export interface NavItem {
  name: string;
  icon: LucideIcon;
  path: string;
  badge?: number;
}

// Admin Navigation Items
export const adminNavItems: NavItem[] = [
  { name: "Dashboard", icon: LayoutDashboard, path: "/admin/dashboard" },
  { name: "Users", icon: Users, path: "/admin/users" },
  { name: "Teachers", icon: GraduationCap, path: "/admin/teachers" },
  { name: "Students", icon: UserCheck, path: "/admin/students" },
  { name: "Guardians", icon: Heart, path: "/admin/guardians" },
  { name: "Moderators", icon: Shield, path: "/admin/moderators" },
  { name: "Courses", icon: BookOpen, path: "/admin/courses" },
  { name: "Batches", icon: Layers, path: "/admin/batches" },
  { name: "Enrollments", icon: ClipboardList, path: "/admin/enrollments" },
  { name: "Posts", icon: FileText, path: "/admin/posts" },
  { name: "Blogs", icon: Newspaper, path: "/admin/blogs" },
  { name: "Quizzes", icon: HelpCircle, path: "/admin/quizzes" },
  { name: "Exams", icon: ScrollText, path: "/admin/exams" },
  { name: "Notes", icon: File, path: "/admin/notes" },
  { name: "Payments", icon: CreditCard, path: "/admin/payments" },
  { name: "Transactions", icon: Receipt, path: "/admin/transactions" },
  { name: "Refunds", icon: RotateCcw, path: "/admin/refunds" },
  { name: "Coupons", icon: Tag, path: "/admin/coupons" },
  { name: "Support", icon: Headset, path: "/admin/support" },
  { name: "Doubts", icon: HelpCircle, path: "/admin/doubts" },
  { name: "Analytics", icon: BarChart, path: "/admin/analytics" },
  { name: "Reports", icon: FileBarChart, path: "/admin/reports" },
  { name: "Activity Logs", icon: Activity, path: "/admin/logs" },
  { name: "Settings", icon: Settings, path: "/admin/settings" },
  { name: "System", icon: Cog, path: "/admin/system" },
  { name: "Audit Logs", icon: History, path: "/admin/audit" },
];

// Teacher Navigation Items
export const teacherNavItems: NavItem[] = [
  { name: "Dashboard", icon: LayoutDashboard, path: "/teacher/dashboard" },
  { name: "My Batches", icon: Layers, path: "/teacher/batches" },
  { name: "Live Sessions", icon: Video, path: "/teacher/live-sessions" },
  { name: "Attendance", icon: CalendarCheck, path: "/teacher/attendance" },
  { name: "Courses", icon: BookOpen, path: "/teacher/courses" },
  { name: "Students", icon: Users, path: "/teacher/students" },
  { name: "Enrollments", icon: ClipboardList, path: "/teacher/enrollments" },
  { name: "Create Post", icon: FilePlus, path: "/teacher/posts/create" },
  { name: "My Posts", icon: FileText, path: "/teacher/posts" },
  { name: "Create Blog", icon: Newspaper, path: "/teacher/blogs/create" },
  { name: "My Blogs", icon: Newspaper, path: "/teacher/blogs" },
  { name: "Upload Notes", icon: FileUp, path: "/teacher/notes/upload" },
  { name: "My Notes", icon: File, path: "/teacher/notes" },
  { name: "Create Quiz", icon: HelpCircle, path: "/teacher/quizzes/create" },
  { name: "My Quizzes", icon: HelpCircle, path: "/teacher/quizzes" },
  { name: "Create Exam", icon: ScrollText, path: "/teacher/exams/create" },
  { name: "My Exams", icon: ScrollText, path: "/teacher/exams" },
  { name: "Assignments", icon: Clipboard, path: "/teacher/assignments" },
  { name: "Quiz Results", icon: Award, path: "/teacher/results/quizzes" },
  { name: "Exam Results", icon: Trophy, path: "/teacher/results/exams" },
  { name: "Grade Assignments", icon: PenLine, path: "/teacher/grade" },
  { name: "Doubt Solving", icon: MessageCircle, path: "/teacher/doubts" },
  { name: "Announcements", icon: Megaphone, path: "/teacher/announcements" },
  {
    name: "Performance",
    icon: TrendingUp,
    path: "/teacher/analytics/performance",
  },
  {
    name: "Student Progress",
    icon: BarChart,
    path: "/teacher/analytics/progress",
  },
  { name: "Profile", icon: User, path: "/teacher/profile" },
  { name: "Schedule", icon: Calendar, path: "/teacher/schedule" },
  { name: "Reviews", icon: Star, path: "/teacher/reviews" },
];

// Student Navigation Items
export const studentNavItems: NavItem[] = [
  { name: "Dashboard", icon: LayoutDashboard, path: "/student/dashboard" },
  { name: "My Batches", icon: Layers, path: "/student/my-batches" },
  { name: "Live Classes", icon: Video, path: "/student/live-classes" },
  { name: "Recorded Lectures", icon: Film, path: "/student/recordings" },
  { name: "Attendance", icon: CalendarCheck, path: "/student/attendance" },
  { name: "Timetable", icon: Clock, path: "/student/timetable" },
  { name: "Notes", icon: File, path: "/student/notes" },
  { name: "Assignments", icon: Clipboard, path: "/student/assignments" },
  { name: "Practice", icon: PenTool, path: "/student/practice" },
  { name: "Formula Sheets", icon: Sigma, path: "/student/formulas" },
  { name: "Quizzes", icon: HelpCircle, path: "/student/quizzes" },
  { name: "Exams", icon: ScrollText, path: "/student/exams" },
  { name: "Test Series", icon: Layers, path: "/student/test-series" },
  { name: "My Results", icon: Award, path: "/student/results" },
  { name: "Ask Doubt", icon: MessageCircle, path: "/student/ask-doubt" },
  { name: "My Doubts", icon: HelpCircle, path: "/student/my-doubts" },
  { name: "Forum", icon: MessagesSquare, path: "/student/forum" },
  { name: "Blogs", icon: Newspaper, path: "/student/blogs" },
  { name: "Media Library", icon: Film, path: "/student/media" },
  { name: "Previous Papers", icon: Archive, path: "/student/papers" },
  { name: "My Progress", icon: TrendingUp, path: "/student/progress" },
  { name: "Performance", icon: BarChart, path: "/student/analytics" },
  { name: "Achievements", icon: Trophy, path: "/student/achievements" },
  { name: "Certificates", icon: Award, path: "/student/certificates" },
  { name: "Fee Details", icon: CreditCard, path: "/student/fees" },
  { name: "Payment History", icon: History, path: "/student/payments" },
  { name: "Invoices", icon: Receipt, path: "/student/invoices" },
  { name: "My Profile", icon: User, path: "/student/profile" },
  { name: "Settings", icon: Settings, path: "/student/settings" },
  { name: "Guardian Info", icon: Heart, path: "/student/guardian" },
];

// Guardian Navigation Items
export const guardianNavItems: NavItem[] = [
  { name: "Dashboard", icon: LayoutDashboard, path: "/guardian/dashboard" },
  { name: "My Children", icon: Users, path: "/guardian/children" },
  { name: "Attendance", icon: CalendarCheck, path: "/guardian/attendance" },
  { name: "Exam Results", icon: Trophy, path: "/guardian/results" },
  { name: "Progress Reports", icon: BarChart, path: "/guardian/progress" },
  { name: "Assignments", icon: Clipboard, path: "/guardian/assignments" },
  { name: "Class Schedule", icon: Calendar, path: "/guardian/schedule" },
  { name: "Upcoming Exams", icon: ScrollText, path: "/guardian/exams" },
  { name: "Holidays", icon: CalendarX, path: "/guardian/holidays" },
  { name: "Announcements", icon: Megaphone, path: "/guardian/announcements" },
  { name: "Messages", icon: Mail, path: "/guardian/messages" },
  { name: "Teacher Notes", icon: MessageSquare, path: "/guardian/notes" },
  { name: "PTM", icon: Users, path: "/guardian/ptm" },
  { name: "Fee Details", icon: CreditCard, path: "/guardian/fees" },
  { name: "Payment History", icon: History, path: "/guardian/payments" },
  { name: "Due Payments", icon: AlertCircle, path: "/guardian/due-payments" },
  { name: "Receipts", icon: Download, path: "/guardian/receipts" },
  { name: "Profile", icon: User, path: "/guardian/profile" },
  { name: "Settings", icon: Settings, path: "/guardian/settings" },
];

// Moderator Navigation Items
export const moderatorNavItems: NavItem[] = [
  { name: "Dashboard", icon: LayoutDashboard, path: "/moderator/dashboard" },
  { name: "My Batches", icon: Layers, path: "/moderator/batches" },
  { name: "Students", icon: Users, path: "/moderator/students" },
  { name: "Attendance", icon: CalendarCheck, path: "/moderator/attendance" },
  { name: "Pending Posts", icon: Clock, path: "/moderator/posts/pending" },
  {
    name: "Reported Content",
    icon: AlertTriangle,
    path: "/moderator/reported",
  },
  { name: "Comments", icon: MessageCircle, path: "/moderator/comments" },
  { name: "Approve Notes", icon: FileCheck, path: "/moderator/notes" },
  { name: "Doubts Queue", icon: HelpCircle, path: "/moderator/doubts" },
  { name: "Support Tickets", icon: Headset, path: "/moderator/support" },
  { name: "Announcements", icon: Megaphone, path: "/moderator/announcements" },
  { name: "Notifications", icon: Bell, path: "/moderator/notifications" },
  { name: "Messages", icon: Mail, path: "/moderator/messages" },
  {
    name: "Attendance Reports",
    icon: FileBarChart,
    path: "/moderator/reports/attendance",
  },
  { name: "Activity Logs", icon: Activity, path: "/moderator/logs" },
  { name: "Profile", icon: User, path: "/moderator/profile" },
  { name: "Settings", icon: Settings, path: "/moderator/settings" },
];

// Map role to navigation items
export const roleNavMap: Record<string, NavItem[]> = {
  SUPER_ADMIN: adminNavItems,
  ADMIN: adminNavItems,
  TEACHER: teacherNavItems,
  STUDENT: studentNavItems,
  GUARDIAN: guardianNavItems,
  MODERATOR: moderatorNavItems,
};
