import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const baseApi = createApi({
  reducerPath: "baseApi",

  baseQuery: fetchBaseQuery({
    baseUrl: "/api",
    credentials: "include",
  }),

  tagTypes: [
    "User",
    "Teacher",
    "TeacherStats",
    "Student",
    "StudentStats",
    "StudentProgress",
    "Guardian",
    "GuardianStats",
    "GuardianStudents",
    "GuardianPreferences",
    "Moderator",
    "ModeratorStats",
    "ModeratorBatches",
    "ModeratorActivity",
    "Course",
    "Batch",
    "Enrollment",
    "BatchMaterial",
    "BatchReview",
    "BatchStats",
    "QuizResults",
    "QuizStats",
    "Quiz",
    "QuizAnalytics",
    "QuizQuestions",
    "QuizAttempts",
    "Exam",
    "ExamStats",
    "ExamResults",
    "ExamResult",
    "Doubt",
    "DoubtStats",
    "DoubtAnswers",
    "DoubtAnswer",
    "Post",
    "MediaStats",
    "PostMedia",
    "PostReactions",
    "PostComments",
    "UserBookmarks",
    "UserCollections",
    "Blog",
    "BlogStats",
    "BlogComments",
    "CommentStats",
    "Note",
    "NoteStats",
    "Payment",
    "PaymentStats",
    "PaymentReceipt",
    "StudentPayments",
    "EnrollmentPayments",
  ],

  endpoints: () => ({}),
});
